version: '3.8'

services:
  crawler-app:
    image: crawler:latest   # Replace with your actual Docker image name
    build:
      context: .                  # Path to the Dockerfile, "." means the current directory
      dockerfile: Dockerfile       # If your Dockerfile is named something other than "Dockerfile", update it
    container_name: crawler-app
    ports:
      - "8080:8080"               # Mapping HTTP port 8080 of the container to the host's 8080
      - "8081:8081"               # Mapping HTTPS port 8081 of the container to the host's 8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development   # Set environment variable for Development (can be Production/Production)
      - ASPNETCORE_HTTP_PORTS=8080            # Specify the port for HTTP (8080)
    networks:
      - crawler-net
    restart: always   # Optionally restart the container if it crashes

networks:
  crawler-net:
    driver: bridge   # This creates a bridge network to link services
