global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: "crawler-app"
    static_configs:
      - targets: ["crawler-app:8080"]